// SEO Configuration for Digital Haridwar
export const siteConfig = {
    name: 'Digital Haridwar',
    description:
        'Leading digital marketing agency in Haridwar offering SEO, social media marketing, PPC, web design, and digital branding services.',
    url: 'https://www.digitalharidwar.com',
    ogImage: 'https://www.digitalharidwar.com/og-image.png',
    links: {
        facebook: 'https://www.facebook.com/digitalharidwar',
        instagram: 'https://www.instagram.com/digitalharidwar',
        linkedin: 'https://www.linkedin.com/company/digitalharidwar',
    },
    keywords: [
        'Digital Marketing Agency in Haridwar',
        'Haridwar Digital Marketing Services',
        'Digital Haridwar Company',
        'Best Digital Agency in Haridwar',
        'SEO Services in Haridwar',
        'Social Media Marketing Haridwar',
        'Website Designing in Haridwar',
        'PPC Services in Haridwar',
        'Google Ads Company in Haridwar',
        'Digital Branding Agency Haridwar',
        'Online Marketing Services Haridwar',
        'Content Marketing Agency Haridwar',
        'Local SEO Services Haridwar',
        'Haridwar Digital Growth Solutions',
        'E-commerce Marketing Haridwar',
        'Haridwar Website Development Company',
        'Facebook Ads Agency Haridwar',
        'Instagram Marketing Haridwar',
        'Digital Transformation Haridwar',
        'Haridwar Online Promotion Services',
        'Performance Marketing Agency Haridwar',
        'Digital Consulting Services Haridwar',
        'Haridwar Creative Digital Agency',
        'Lead Generation Services Haridwar',
        'Haridwar SEO Company',
        'Digital Strategy Experts Haridwar',
        'Haridwar Digital Business Solutions',
        'Professional Digital Services Haridwar',
        'Marketing Automation Haridwar',
        'Affordable Digital Agency Haridwar',
    ],
}

export const structuredData = {
    organization: {
        '@context': 'https://schema.org',
        '@type': 'Organization',
        name: 'Digital Haridwar',
        url: 'https://www.digitalharidwar.com',
        logo: 'https://www.digitalharidwar.com/logo.png',
        description: siteConfig.description,
        address: {
            '@type': 'PostalAddress',
            streetAddress:
                '184, Subhash Nagar, Shankar Ashram, Alankar complex, Jwalapur',
            addressLocality: 'Haridwar',
            addressRegion: 'Uttarakhand',
            postalCode: '249407',
            addressCountry: 'IN',
        },
        contactPoint: {
            '@type': 'ContactPoint',
            telephone: '+91-82189-11085',
            contactType: 'Customer Service',
            email: 'yogeshggangwar@gmail.com',
            areaServed: 'IN',
            availableLanguage: ['English', 'Hindi'],
        },
        sameAs: [
            siteConfig.links.facebook,
            siteConfig.links.instagram,
            siteConfig.links.linkedin,
        ],
        aggregateRating: {
            '@type': 'AggregateRating',
            ratingValue: '4.9',
            reviewCount: '150',
            bestRating: '5',
            worstRating: '1',
        },
    },
    localBusiness: {
        '@context': 'https://schema.org',
        '@type': 'LocalBusiness',
        name: 'Digital Haridwar',
        image: 'https://www.digitalharidwar.com/logo.png',
        '@id': 'https://www.digitalharidwar.com',
        url: 'https://www.digitalharidwar.com',
        telephone: '+91-82189-11085',
        priceRange: '₹₹',
        address: {
            '@type': 'PostalAddress',
            streetAddress:
                '184, Subhash Nagar, Shankar Ashram, Alankar complex, Jwalapur',
            addressLocality: 'Haridwar',
            addressRegion: 'Uttarakhand',
            postalCode: '249407',
            addressCountry: 'IN',
        },
        geo: {
            '@type': 'GeoCoordinates',
            latitude: 29.9457,
            longitude: 78.1642,
        },
        openingHoursSpecification: {
            '@type': 'OpeningHoursSpecification',
            dayOfWeek: [
                'Monday',
                'Tuesday',
                'Wednesday',
                'Thursday',
                'Friday',
                'Saturday',
            ],
            opens: '09:00',
            closes: '18:00',
        },
    },
}
